### PR TITLE
add login by role

### PR DESCRIPTION
**Pull request by kuisskui**
Test by logging in by signing up as normal. and login by GitHub then check the differences.

### CODE REVIEW

**Comment by kuisskui** [comment]
@teenteennnii review please

**Comment by teenteennnii** [comment]
After testing, the role system of normal login is all green. but when you login with github, user not store in user table and it causes that use not have role.

This pic is login with github.
Screenshot 2567-04-15 at 08 16 36

This pic is normal login.
Screenshot 2567-04-15 at 08 18 12

The problem is when you need ROLE_USER, the user from github will cannot access it.
I think if you dont want to fix it, just dont use ROLE_USER to access anything in the app.

**Comment by teenteennnii** [comment]
If you dont fix this feature, you can go merge

**Comment by kuisskui** [comment]
Oh,I stuck the recording of third party user for days. I move on for now. Can you try to just find the way to recording the third party user detail into the database.

**Comment by kuisskui** [comment]
Oh,I stuck the recording of third party user for days. I move on for now. Can you try to just find the way to recording the third party user detail into the database.

**Pull request merged**
